src/v2/spec.yaml

(mistakenly builds on top of the notifications v2 oas spec)

Spec for relevant followers

---

src/v1/spec.yaml
src/v2/spec.yaml

includes spec for:
- Neynar frame pages 
- Neynar frames 
- GET, POST, PUT, DELETE routes for Neynar frames 
Does not include:
- flex_url as an action_type

OAS spec for frame routes

---

src/v2/spec.yaml

- Update NeynarFrameUpdateRequest schema

Update NeynarFrameUpdateRequest schema

---

src/v2/spec.yaml

updates the docs for bulk-by-address to include address_types

Update bulk-by-address endpoint

---

src/v2/spec.yaml

- Feed endpoint viewer FID changes

 Feed endpoint viewer FID changes

---

src/v2/spec.yaml

Add following properties in `WebhookSubscriptionFilters`
- follow.created
- follow.deleted
- reaction.created
- reaction.deleted
Remove unused tags
- Neynar Frames
- Signer (Developer Managed)

reactions-follow-created-deleted-webhooks

---

src/v2/spec.yaml

- nodejs sdk: https://github.com/neynarxyz/nodejs-sdk/pull/101
- removes limit from query for notifications

removes limit for notifications

---

src/v2/spec.yaml

nodejs-sdk: https://github.com/neynarxyz/nodejs-sdk/pull/102
adds channel_id param to  feed/trending

remove limit param from feed/trending and adds channel_id

---

src/v2/spec.yaml

followers OAS

---

src/v2/spec.yaml

fixes channel_follow_context to have a better description.

reword channel_follow_context description

---

src/v2/spec.yaml

- switch /farcaster/followers FollowSortType to be an enum

switch FollowSortType pattern to enum

---

src/v2/spec.yaml

- limits were incorrect for /v2/following and /v2/followers

fix limit bugs for follow and following

---

src/v2/spec.yaml

fix: make channelType a schema

---

src/v2/spec.yaml

- add parent_author_fid to body (required is false) for cast post

add parent_author_fid to body

---

src/v2/spec.yaml

Revert "Kevin/neyn 1404 frame api needs to support more action types"

---

src/v2/spec.yaml

- adds viewer context to cast with interactions (its optional)

add viewer_context to castwithinteractions

---

src/v2/spec.yaml

makes a type for userviewercontext

add viewer context object for user

---

src/v2/spec.yaml

adds viewer_fid to /conversation and /cast

add viewer fid to conversation and cast

---

src/v2/spec.yaml

- adds viewer fid to bulk by address

adds viewer fid to bulk by address

---

src/v2/spec.yaml

change example fids to not be dwr

change example fids to not be dwr for subscriptions

---

src/v2/spec.yaml

adds /user/subscribed_to
adds viewer_fid to /user/subscribers

subscribed_to and viewer fid

---

src/v2/spec.yaml

- switch user to creator
- change subscribers to subscriptions_created
- add defaults to fid

switch user to creator

---

src/v2/spec.yaml

add back frame type to response

add back frame type to response

---

src/v2/spec.yaml

add subscription providers for /subscribers

---

src/v2/spec.yaml

adds is_priority to notifications

add is_priority

---

src/v2/spec.yaml

OAS changes for https://github.com/neynarxyz/api/pull/517
The README is pretty sparse. Running the `openapi-generator` command did nothing. Not sure if there's anything else I need to do.

Add new `/v2/farcaster/feed/for_you` OpenAPI spec [NEYN-1882]

---

src/v2/spec.yaml

related API change that should be merged first: https://github.com/neynarxyz/api/pull/527

OAS change for viewer_fid on user/power

---

src/v2/spec.yaml

change tier to subscription tier

change tier to subscription tier

---

src/v2/spec.yaml

add-exclude_author_fids-in-WebhookSubscriptionFilters

add-exclude_author_fids-in-WebhookSubscriptionFilters

---

src/v2/spec.yaml

- add subscribed_at to subscribed responses

add subscribed_at

---

src/v2/spec.yaml

Counterpart to https://github.com/neynarxyz/api/pull/592
I ran both the commands in the README and it resulted in no generated file changes in this repo. I don't remember if there are supposed to be or not. Something's wrong if so.

Add EmbedUrlMetadata optional subobject to EmbedUrl [NEYN-2116]

---

src/v2/spec.yaml

- add protocol version to subscribed_to
- sdk change: https://github.com/neynarxyz/nodejs-sdk/pull/143

add protocol version

---

src/v2/spec.yaml

- add stp subscription check docs

add docs for subscription check

---

src/v2/spec.yaml
src/v2/stp/spec.yaml

make stp section

---

.github/workflows/rdme-openapi.yml
README.md
src/v2/spec.yaml
src/v2/stp/spec.yaml

set up github action for stp
add relevant error types

set up github action

---

src/v2/spec.yaml

OAS changes for https://github.com/neynarxyz/api/pull/632

Embed URL image/video metadata [NEYN-2426]

---

src/v2/spec.yaml

docs for warpcast composer action list

compose action list docs

---

src/v2/spec.yaml

- use Cast tag and have operation id match

clean up tag

---

src/v2/spec.yaml

API PR: https://github.com/neynarxyz/api/pull/635

Add HTML metadata (adapted from open-graph-scraper Typescript) [NEYN-2537]

---

src/v2/spec.yaml

- add description object to dehydrated channel

add description to dehydrated channel

---

src/v2/spec.yaml

This endpoint returns users who are blocked by the given fid (or are blocking the given fid)

feat: add `block/list` endpoint

---

src/hub-rest-api/spec.yaml

this PR adds example values to all methods except submit/validate message POSTs for the Hub REST API

add: example values to all methods except submit/validate message POSTs for hub REST api

---

README.md
src/v1/spec.yaml
src/v2/stp/spec.yaml

adds `x-api-key` for v1 and STP APIs

add `x-api-key` for v1 and STP APIs

---

src/v2/spec.yaml

This PR adds the new `/v2/farcaster/channel/followers/relevant` endpoint

docs: add '/v2/farcaster/channel/followers/relevant' route

---

src/v2/spec.yaml

docs: add example inputs for '/v2/farcaster/channel/followers/relevant

---

src/v2/spec.yaml

fix: id param should be string

---

src/v2/spec.yaml

now it picks up from OAS instead of being hardcoded

fixing description, there was an error in limit

---

src/v1/spec.yaml
src/v2/spec.yaml

- adds new endpoint `/v2/farcaster/user/by_username`
- deprecates `/v1/farcaster/user-by-username`
related api changes: https://github.com/neynarxyz/api/pull/849

docs: add new endpoint '/v2/farcaster/user/by_username'

---

src/v2/spec.yaml

Adds documentation for the new `/v2/farcaster/user/memberships/list` endpoint

docs: add '/v2/farcaster/user/memberships/list' endpoint

---

src/v2/spec.yaml

adding fold param to /conversation api

---

src/v2/spec.yaml

Add OAS for cast.deleted
`cast.deleted` filter has been introduced into webhooks
- `WebhookSubscriptionFiltersCast` - New Schema for a cast filter for in webhooks.
- `WebhookSubscriptionFilters` - Modified to include additional fields `cast.deleted`

Add oas for cast.deleted

---

src/v2/spec.yaml

Add the `verified_accounts` fields to the user schema.
- `UpdatedSchema` - `User`

update user schema to include verified accounts

---

src/v2/spec.yaml

Securely communicate and perform actions on behalf of users across different apps
Add endpoint for Farcaster action
- `POST - /v2/farcaster/action` - Securely communicate and perform actions on behalf of users across different apps
- `FarcasterActionReqBody` - Schema for  /v2/farcaster/action request body.

Add endpoint for Farcaster action

---

src/v2/spec.yaml

- OAS changes corresponding to the API changes here: https://github.com/neynarxyz/api/pull/936
- Also fixed a number of obvious bugs in how we were trying to do inheritance (we were using `anyOf` instead of `allOf`)

OAS changes for embedded casts; plus other fixes [NEYN-2641]

---

src/v2/spec.yaml

adds a new endpoint for suggested follows
- `GET /v2/farcaster/following/suggested`

docs: add '/v2/farcaster/following/suggested' api

---

src/v1/spec.yaml
src/v2/spec.yaml

related api change here: https://github.com/neynarxyz/api/pull/957
remove active status from user objects

removing active badge from user object

---

src/v2/spec.yaml

Allowlist opengraph tags and introduce oembed [NEYN-3312; NEYN-3542]

---

src/v2/spec.yaml

Fixup cast_id causing Readme workflow failure

Fix cast_id

---

src/v2/spec.yaml

Migrate OAS to v3.1.0

---

openapi-generator-config.json

https://neynar.slack.com/archives/C0653FSDW9H/p1730253325755779?thread_ts=1730214092.598719&cid=C0653FSDW9H

Split generated code into individual files again

---

src/v2/spec.yaml

Add the `/user/by_location` route, to find users by latitude and longitude.
- `GET /user/by_location` - Fetches users near the provided latitude and longitude. Uses existing schemas for the output.

feat: add /user/by_location route

---

src/v2/spec.yaml

Add the `x-neynar-experimental` header flag.
-  All endpoints can accept the new header
- `NeynarExperimentalHeader` is an optional boolean that determines whether to enable experimental features

feat: add experimental header flag

---

src/v2/spec.yaml

Define the schema of the experimental output w/ Neynar user score.
- `User` schema updated to include `experimental.neynar_user_score`

feat: define experimental output schema

---

src/hub-rest-api/spec.yaml

Update hub oas version to 3.1.0 and update operationId

Update hub oas to v3.1.0 and Update operationId

---

src/v2/spec.yaml

Adds the `/user/balance` route and associated schemas.
Add
- `GET /v2/farcaster/user/balance` - Gets the balances of tokens on base by fid.
- `TokenBalance`: Object containing token metadata and a balance in the token and in USDC.
- `AddressBalance`: Object containing an address and all of it's `TokenBalances` on a network.
- `BalanceResponse`: Object containing a dehydrated user and an array of all of their `AddressBalance`s.
Need updated instructions on validating.

feat: add `/user/balance` route

---

.github/workflows/validate-oas.yml
.spectral.yaml
README.md
src/hub-rest-api/spec.yaml
src/v1/spec.yaml
src/v2/spec.yaml

fix: add ruleset

---

src/v2/spec.yaml

feat: relevant fungible owners

---

src/v2/spec.yaml

Add OAS for deploy fungible

---

src/v2/spec.yaml

See https://github.com/neynarxyz/monorepo/pull/1075 and https://linear.app/neynar/issue/NEYN-3523/new-api-for-embed-metadata-fetching

OAS changes for new v2/farcaster/cast/embed/crawl API [NEYN-3523]

---

src/v2/spec.yaml

Add clanker as a provider

---

src/v2/spec.yaml

https://github.com/neynarxyz/monorepo/pull/1209

Include disabled tokens in response [NEYN-3985]

---

src/v2/spec.yaml

Document limit on number of channel ids that can be requested in a feed

document limit on number of channel ids

---

src/v2/spec.yaml

Updated doc string for `/cast/search` `q` param to include search commands for a range of time.

feat: add ability to search casts by a date range

---

src/v2/spec.yaml

https://neynar.slack.com/archives/C047N4VDCCV/p1738617107014379

Loosen up Frames v2 specs fit frame-core code

---

src/v2/spec.yaml

Also add legacy frame v2 version values

Add frame to embed

---

src/v2/spec.yaml

https://github.com/neynarxyz/monorepo/pull/1366

Add user/interactions

---

src/v2/spec.yaml

https://github.com/neynarxyz/monorepo/pull/1397

Add mention range

---

src/v2/spec.yaml

Per @rishavmukherji request in Linear comment https://linear.app/neynar/issue/NEYN-4418/[bug]-fid-fid-interaction-history-returning-all-interactions-instead#comment-bb36fc37

Add Agents category/tag

---

src/v2/spec.yaml

See https://github.com/neynarxyz/monorepo/pull/1410

Add `app_fid` filter param to `/v2/farcaster/feed/user/casts` [NEYN-3926]

---

src/v2/spec.yaml

See https://github.com/neynarxyz/monorepo/pull/1438

Add the now-working `limit` param to the three `/notifications*` APIs [NEYN-4540]

---

src/v2/spec.yaml

New APIs for creating and fetching a transaction frame

feat: New APIs for creating and fetching a transaction frame

---

src/v2/spec.yaml

More detail on supported options for `mode` and `sort_type`. Changes to descriptions only - no endpoint or schema changes.

docs: more detail on new search options

---

src/v2/spec.yaml

Add Neynar as a For You feed provider and make it the default.
- `ForYouProvider` - Add `neynar` to the enum and set as default.
Note: this has 2 version bumps compared to main - is based off of https://github.com/neynarxyz/OAS/pull/301 and is meant to be merged after #301.
I'll drop the version bump from this PR if we decide to merge both of these PRs with one version bump.

feat: add Neynar as For You feed provider, new default

---

src/v2/spec.yaml

Counterpart to https://github.com/neynarxyz/monorepo/pull/1568

Adding profiles/channels mentioned in user bios

---

src/v2/spec.yaml

[NEYN-4882] - Algorithmic feed support by parent URL

---

src/v2/spec.yaml

Add experimental header flag to several endpoints.
- Several endpoints updated to add the `x-neynar-experimental` header flag.

add experimental header to several routes

---

.github/workflows/oas-to-docs-pr.yaml

No change to spec.  This is a new workflow to publish the yaml specs to the docs repository to then be ingested by Mintlify

New workflow to copy YAML changes to docs repo

---

.github/workflows/oas-to-docs-pr.yaml

No spec changes.  Continuing to work on the new OAS-to-docs worfklow

Update oas-to-docs-pr.yaml with persist-credentials: true

---

src/v2/spec.yaml

First wave of OpenAPI mistakes I've found while doing Typescript proof-of-concept work. Generally fixes syntax errors and obvious mismatches with actual neynar-api behavior.

First wave of OAS fixes coming out of Typescript work [NEYN-3578]

---

src/v2/spec.yaml

This PR updates the OAS to support [this monorepo PR](https://github.com/neynarxyz/monorepo/pull/1667).
* updated `/v2/farcaster/following` endpoint to support new `sort_type=affinity_score`
* added new route `/v2/farcaster/frame/relevant` to serve relevant frames to the user based on affinity viewer_id has for various users
* added new route `/v2/farcaster/frame/relevant` to serve relevant frames to the user based on affinity viewer_id has for various users
* updated `/v2/farcaster/following` endpoint to support new `sort_type=affinity_score`
n/a
- `UpdatedSchema` - Updated `SortType` to include `affinity_score`

relevant frames

---

src/v2/spec.yaml

add operator docs for /farcaster/cast/search
description/example for search operatiors

add operator docs for /farcaster/cast/search

---

src/v2/spec.yaml

Added /farcaster/user/by_x_username to lookup users by X username
- `GET /v2/farcaster/user/by_x_username` - Description of the new endpoint.

Add farcaster/user/by_x_username route

---

src/v2/spec.yaml

Shortened the summary of the new by-x-username endpoint

---

src/v2/spec.yaml

This PR updates "frame" references to "miniapp" in the titles and descriptions of the OAS (not routes, params, or object names)

refactor: "frame" to "miniapp"

---

src/v2/spec.yaml

Add score in User schema

---

src/v2/spec.yaml

Make viewer fid optional and update description for /fungible/owner/relevant

---

src/v2/spec.yaml

Add `x-neynar-experimental` header to `/cast/metrics` endpoint. It was already present in the `/cast/search` endpoint.
- `GET /casts/metrics`

feat: add experimental header to metrics endpoint

---

src/v2/spec.yaml

POST - /farcaster/user/register - [NEYN-5207]

---

src/v2/spec.yaml

fix transaction hash example

---

src/v2/spec.yaml

Rename follow sort_type affinity_score -> algorithmic

---

src/v2/spec.yaml

This PR adds a description to the `following_fid` filter param.

fix: add comment to following_fid

---

src/v2/spec.yaml

Another API <-> OAS mismatch bug discovered while doing ts-rest work

Fix bug with `/v2/farcaster/fungible/owner/relevant` found during TS work
