src/v2/spec.yaml
modify the description of the "/channel/trending" api, the default value should be 10, and the max value should be 25.
=> Update the description of api in spec.yaml

src/v2/spec.yaml
- allows the user to search for a channel with either a parent_url or id
=> add type to /channel

src/v2/spec.yaml
- fixes type for channels/search
=> fix: /channel/search now uses ChannelSearchResponse

src/v2/spec.yaml
fixes the inputs of GET `/v2/frame` given the new changes to the route that allow for `type` to be either `uuid` or `url`
=> fix: add new frame route params

src/v2/spec.yaml
- next was inside the conversation property when this isn't accurate
=> next shouldn't be inside conversation

src/v2/spec.yaml
Reapply "Kevin/neyn 1274 add oas to update to have one of dehydrated or full (#89)"
This reverts commit 00e2097c1bd317b86fc72fc3ff34f417fe536bb6.
Doc changes for https://github.com/neynarxyz/api/pull/509
=> Doc changes for adding channel_dehydrated object back to v2/farcaster/cast API responses [NEYN-1258]

src/v2/spec.yaml
This PR removed the `is_priority` parameter from all 3 `notifications` endpoint docs.
=> docs: remove is_priority from notifications API docs

src/v2/spec.yaml
This PR adds documentation for the new `/feed/parent_urls` endpoint
=> docs: add docs for /feed/parent_urls endpoint

src/v1/spec.yaml, src/v2/spec.yaml
This PR adds docs for the new `/v2/farcaster/feed/user/recent` endpoint
=> docs: add docs for /v2/farcaster/feed/user/recent endpoint

src/v1/spec.yaml
fast follow to https://github.com/neynarxyz/OAS/pull/171
Corrects an issue where the v1 deprecation redirect was pointing to the wrong URL. It now points correctly to https://docs.neynar.com/reference/feed-user-casts
=> docs: redirect /v1/casts to the correct v2 endpoint

src/v2/spec.yaml
Adds `include_replies` flag to `/v2/farcaster/feed/user/casts` endpoint
=> docs: add 'include_replies' field to  endpoint

src/v2/spec.yaml
For specifying the type that is wanted from the notifications endpoint, all valid options are plural: follows, recasts, likes, mentions, replies.
For the output provided by the notifications endpoint, some are plural: follows, recasts, likes. The others are singular: mention, reply.
=> different notification enums for input and output

src/v2/spec.yaml
Introducing a warpcast power user backwards compatible endpoint that returns a list of FIDs. No pagination, no frills, no response changes. Just a plug & play replacement for the now deprecated [`https://api.warpcast.com/v2/power-badge-users` endpoint](https://docs.farcaster.xyz/reference/warpcast/api#get-all-power-badge-users)
=> docs: add docs for `/v2/farcaster/user/power-lite` endpoint

src/hub-rest-api/spec.yaml
adds a modified version of [Standard Crypto's Hub REST API OAS schema](https://github.com/standard-crypto/farcaster-js/blob/develop/packages/farcaster-js-hub-rest/src/openapi/spec.yaml) with the Neynar Hub API link and authentication set up
=> add: `spec.yaml` for Hub REST API

.github/workflows/rdme-openapi.yml
this PR ensures that the hub http OpenAPI `spec.yaml` gets properly added to our Readme through the `rdme-openapi.yaml` GitHub action
=> add: ensures hub http spec is in the OpenAPI Github Action

src/hub-rest-api/spec.yaml
ensures a proper `x-api-key` header is set for the Raw Farcaster Hub API documentation
=> add: ensure `x-api-key` header is properly set for hub rest api docs

src/v2/spec.yaml
Adds a `sort_type` query param to the `/v2/farcaster/cast/conversation` endpoint. Supports both `desc_chron` (default) and `algorithmic`. Algorithmic is based on engagement
Related API change: https://github.com/neynarxyz/api/pull/842
=> feat: add 'sort_type' param to /cast/conversation

src/v1/spec.yaml, src/v2/spec.yaml
For some reason, https://docs.neynar.com/reference/user-by-username is still redirecting to https://docs.neynar.com/reference/user-by-username-v1 even after changing the operation id in https://github.com/neynarxyz/OAS/pull/210. 
This PR introduces https://docs.neynar.com/reference/user-by-username-v2 instead for the `/v2/farcaster/user/by_username` route as a workaround
=> fix: use new, unique operation name for 'v2/user/by_username'

src/v2/spec.yaml
`ChannelMember`, used in many of the channel APIs is now of a format:
- `role`
- `channel_id` (DEPRECATED)
- `channel` (one of `Channel` or `DehydratedChannel`
- `user` (one of `User` or `UserDehydrated`
=> docs: update ChannelMember object to include hydrated/dehydrated channel/user

src/v2/spec.yaml
Another bug reported by Coinbase
=> open-graph-scraper actually returns string for all embedded URL meta tags [NEYN-3302]

src/v2/spec.yaml
Adds the missing 200 response docs to `/v2/farcaster/user/by_username` endpoint
=> fix: add 200 response to '/v2/farcaster/user/by_username'

src/v2/spec.yaml
This PR removes 'ChannelMember.channel_id' in favor of 'ChannelMember.channel.id'
=> docs: remove 'ChannelMember.channel_id' in favor of 'ChannelMember.channel.id'

.github/PULL_REQUEST_TEMPLATE.md, src/v2/spec.yaml
Fix the issue of 200 response not rendering for `/cast/converstion`
Add a schema to create a copy of the original schema that refers to itself, but replace the self-reference with an empty object. In the original schema, replace the self-reference with a reference to this additional schema to resolve the recursive object issue.
- `CastWithInteractionsAndConversationsRef` - Schema that points to CastWithInteractionsAndConversations
- `CastWithInteractionsAndConversations` - Modified to refer CastWithInteractionsAndConversationsRef rather that itself
=> Fix `/cast/conversion` response in readme

src/v2/spec.yaml
Adds `blocking`, `blocked_by`, and `muted` to the viewer context object.
- `UserViewerContext` - has new keys added: `blocking`, `blocked_by`, and `muted`
=> docs: user viewer context now includes mutes and blocks

src/v2/spec.yaml
This reverts commit b713a63c33edd995d0b767eb963b2008a5dadceb.
This introduces the OAS documentation for `/v2/farcaster/conversation` endpoint with `?fold=` flag
Adds optional `?fold=` flag to `/v2/farcaster/conversation`
n/a
- `GET /v2/farcaster/conversation` - Added query param `fold` which can be either `above` or `below`
n/a
n/a
=> docs: add '?fold' flag to '/conversation'

src/v2/spec.yaml
Very small change to remove the `muted` key from the `UserViewerContext`. This change is to keep mutes private.
=> fix: remove muted from viewer_context

src/v2/spec.yaml
Adds `BlockRecord` and `MuteRecord`, which are copies of `BlockList` and `MuteList`. The latter are marked deprecated. Change `BanList` to `BanRecord`. We're changing `List` to `Record` because these items are not arrays, they are the items in the arrays so the new name is more intuitive.
- `BlockRecord`
- `MuteRecord`
=> add more aptly named types for Mutes and Blocks

src/v2/spec.yaml
corrects /v2/farcaster/cast/conversation's default sort type enum as 'chron'
- `GET /v2/farcaster/cast/conversation`
- added sort_type 'chron'
- updated default sort_type to 'chron' -- this is just a naming fix, it doesn't change the behavior
=> docs: update /v2/farcaster/cast/conversation's default sort type enum to 'chron'

src/v2/spec.yaml
Add the `ChannelUserContext` object and deprecate `ChannelViewerContext`. `ChannelUserContext` replaces `ChannelViewerContext` in the hydrated channel. It's also added to the dehydrated channel and the `CastWithInteractions` as `author_channel_context`.
- `ChannelViewerContext`
=> add channel user context for viewer context and author context

src/v2/spec.yaml
Adds latitude and longitude as inputs to `PATCH /user`
- `PATCH /user` - Now accepts `latitude` and `longitude`.
- `UpdateUserReqBody` - Modified to include additional fields: `latitude` and `longitude`
=> doc: add latitude and longitude inputs for PATCH /user

src/v2/spec.yaml
- Fix embedded cast type (`CastEmbedded`), changing `metadata` to `cast` at Coinbase's request (BREAKING CHANGE) [NEYN-3521]
- This requires more duplicated code than expected to ensure there are no circular refs since those break Readme
- Add `channel` field to CastEmbedded [NEYN-3525]
- Add `author` (`UserDehydrated`) field to `CastDehydrated`
- Needed for `CastDehydrated` to fully replace deprecated `CastId` object for embedded casts
=> Embedded cast tweaks [NEYN-3541; NEYN-3525]

src/v2/spec.yaml
Adds `POST /block` and `DELETE /block` routes to block and unblock accounts.
- `POST /v2/farcaster/block` - Block the specified fid for the user associated with the signer
- `DELETE /v2/farcaster/block` - Unblock the user
- `BlockReqBody` - Input for both new endpoints, takes a signer_uuid and a blocked_fid.
=> feat: add endpoints for blocking and unblocking

src/v2/spec.yaml
Since global headers aren't supported by Open API, this PR adds the experimental flag to several endpoints, focused on endpoints that return lists of users.
- Various user endpoints updated to include this param
=> feat: add experimental header param to endpoints that return user lists

.github/PULL_REQUEST_TEMPLATE.md, src/v2/spec.yaml
Add 2 new endpoints
- `GET /v2/farcaster/login/nonce` - Fetch nonce to sign message
- `GET /v2/farcaster/signer/list` - Fetch signer list for a custody address
=> Add OAS for `/signer/list` and `/login/nonce`

src/v2/spec.yaml
https://github.com/neynarxyz/monorepo/pull/1150
=> Add `GET frame/notification_tokens` [NEYN-3953]

src/v2/spec.yaml
Add optional `fids` param to `/v2/feeds/channels`
- `GET /v2/farcaster/feed/channels` - Added optional `fids` param.
=> feat: filter channel feeds by fids

src/v2/spec.yaml
Documents the new `/v2/farcaster/cast/metrics` endpoint, which returns counts of casts matching a query per unit time.
- `GET /v2/farcaster/cast/metrics` - Get the number of casts matching a query over time.
- `CastsMetrics` - Object defining one datapoint in time
- `CastsMetricsResponse` - Response type of the new endpoint, contains an array of `CastsMetrics`
=> feat: endpoint to get metrics of casts matching a query

src/v2/spec.yaml
- Frame v1 & Frame v2 objects share 3 properties: version, image, frames_url.
- Added [discriminated union](https://swagger.io/docs/specification/v3_0/data-models/oneof-anyof-allof-not/) for Frame v1 & Frame v2 since both objects have different shape to enable proper typing in SDK and clear distinction in the docs. I verified that Readme.io [supports it](https://docs.readme.com/main/docs/openapi-compatibility-chart#schema-object).
Implementation: https://github.com/neynarxyz/monorepo/pull/1277
=> Add frames/catalog endpoint [NEYN-4193]

src/v2/spec.yaml
Missed change from https://github.com/neynarxyz/monorepo/commit/c6b3e839bbd0e2425b55b615273b02907556dc45
=> Mark image_url as optional in FrameEmbed

src/v2/spec.yaml
Reflect the addition of app info to returned cast objects in https://github.com/neynarxyz/monorepo/pull/1369
Adds new field named `app:` to cast response objects of type `UserDehydrated`. Specifies which Farcaster client app, e.g. Warpcast, Supercast, Neynar, the cast was created through.
=> Add new `app:` UserDehydrated subobject to cast response objects [NEYN-3926]

src/v2/spec.yaml
Adds a query param `mode` to the `/cast/search` endpoint which allows the selection of `literal`, `semantic`, or `hybrid` search.
- `GET /cast/search` - Add `mode` param.
=> feat: semantic and hybrid search of casts

src/v2/spec.yaml
Add the `sort_type` parameter to `/casts/search` which can be `desc_chron` or `algorithmic`
- `GET /casts/search` - Adds `sort_type` so devs can specify `desc_chron` (current behavior and default) or `algorithmic`, which is a new option.
- `SearchSortType` - This is an alias of `FollowSortType` but uses a new name to avoid breaking changes.
LMK if there's a better approach to managing the sort type objects. My best guess was that creating an alias for `FollowSortType` was better than changing the name of that type.
=> feat: algorithmic cast search

.github/workflows/oas-to-docs-pr.yaml
Minor fix to the OAS-to-docs workflow.  The token got vibe-deleted at some point.  re-added.
=> Added token to docs repo fetch call

src/v2/spec.yaml
- Included two new properties of the Channel schema
- Renamed `CastTextRange` to just `TextRange` because its used outside the context of Casts
- Bumped spec version to 2.30.0
- `Channel` - Modified to include additional fields.
=> Added mention values to Channel schema per NEYN-3324

src/v2/spec.yaml
This PR adds `FrameV2WithFullAuthor` to reflect what we've already been returning from any endpoint using `get_v2_users_from_fids` / `getV2UsersFromFids`
- `GET /farcaster/frame/catalog` - Updated frame author object
- `GET /farcaster/frame/relevant` - Updated frame author object
Couldn't make it work by extending FrameV2, as it wasn't overwriting the author object.
=> fix: add FrameV2WithFullAuthor for some frame endpoints

src/hub-rest-api/spec.yaml
Changes the OAS spec for V1/Hubs to be consistent with the new snapchain enum
- `reactionsByTarget` - `ReactionType` no longer required
- `ReactionType` - Updated `ReactionType` enum scheme to be `Like` vs `REACTION_TYPE_LIKE` for each case.
=> chore: change reaction type enum names

src/v2/spec.yaml
This PR adds the externalDocs URL for the relevant frames endpoint, which I forgot in my initial PR #310
=> fix: add externalDocs for relevant frames

.github/workflows/oas-to-go-sdk-pr.yaml, .github/workflows/oas-to-nodejs-sdk-pr.yaml, .github/workflows/oas-to-rust-sdk-pr.yaml
As requested, workflows now request reviews from the latest OAS committer. Additionally, workflows exit cleanly if there are no diffs.
I've validated that PRs are generating when diffs exists and the workflow exits successfully wihout creating PRs when they don't.
The reviewer is chosen as the author of the branch HEAD. the action looks up the username and posts a review request for them.
n.b. it might be more maintainable to utilize the github cli, since it obviates all the jq formatting
=> Add Go workflow and request reviews on all workflows

.github/workflows/oas-to-go-sdk-pr.yaml, .github/workflows/oas-to-rust-sdk-pr.yaml
the rust and go scripts rely on this to populate the packaging with the
correct versioning for publishing.
=> export SDK_VERSION to generate script

src/v2/spec.yaml
Add new endpoint `/farcaster/frame/search` for NEYN-4888
GET `/farcaster/frame/search` - search frames by simple text search across name, description and tags
=> Add /farcaster/frame/search endpoint

src/v2/spec.yaml
This PR moves the default value out of `TrendingTimeWindow` and into each route that uses it.
- `GET /frame/catalog` - Updated default time_window to 7d
- `GET /frame/relevant` - Updated default time_window to 7d
=> fix: make time_window defaults route specific

src/v2/spec.yaml
Added notification filters for `POST /farcaster/frame/notification`, related to this [monorepo PR](https://github.com/neynarxyz/monorepo/pull/1815).
=> feat: broadcast notification filters

src/v2/spec.yaml
change to `fids` param description on this api: https://api.neynar.com/v2/farcaster/frame/notification_tokens
=> changing description for param that was confusing to users

src/v2/spec.yaml
go/rust SDK generation has poor support for `oneOf` so this PR is attempting to remove the latest offense.  The target param is just a string with an example that includes both types.  Also added multiple service-level examples that show up in the sample curl box, which is kinda nice?
changed spec of target param in:
- POST /farcaster/reaction -
- DELETE /farcaster/reaction
- #/components/schemas/ReactionReqBody - Modified target param
=> Update POST /reactions spec for target property to avoid using oneOf

src/v2/spec.yaml
Add new options for cast metrics intervals: 90d and 180d.
=> feat: add 90d & 180d intervals to cast metrics

src/v2/spec.yaml
This PR adds new routes for tracking notification opens and getting related statistics.
- `GET /farcaster/frame/notifications` - Get stats for one or more notification campaigns.
=> add new routes for notification open tracking [NEYN-5381]
